name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy-to-pages:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Git user configs
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Switch to deploy branch and force merge main
        run: |
          git fetch origin
          git checkout -B deploy
          git reset --hard origin/main

      - name: Build Sample Web
        run: |
          ./gradlew :sample:app:web:jsBrowserProductionWebpack

      - name: Move dist to root/docs
        run: |
          DOCS_DIR=docs
          BUILD_DIR=sample/app/web/build/kotlin-webpack/js/productionExecutable

          rm -rf $DOCS_DIR
          mkdir -p $DOCS_DIR

          cp -r $BUILD_DIR/* $DOCS_DIR/
          cp -r sample/app/web/build/processedResources/js/main/* $DOCS_DIR/

      - name: Add CNAME file
        run: echo "animate.nomanr.com" > docs/CNAME

      - name: Force push changes to deploy branch
        run: |
          git add docs
          git commit -m "Deploy to GitHub Pages from commit ${{ github.sha }}"
          git push --force origin deploy